# Configuration for labeler - https://github.com/actions/labeler

cmdlets:
  - changed-files:
    - any-glob-to-any-file: 'src/Commands/**'

tests:
  - changed-files:
    - any-glob-to-any-file: 'tests/**'

ci-cd:
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/**'

docs:
  - changed-files:
    - any-glob-to-any-file: 'docs/**'
    - any-glob-to-any-file: '*.md'

build:
  - changed-files:
    - any-glob-to-any-file: '*.build.ps1'
    - any-glob-to-any-file: '*.csproj'
    - any-glob-to-any-file: '*.sln'

vscode:
  - changed-files:
    - any-glob-to-any-file: '.vscode/**/*'

devcontainer:
  - changed-files:
    - any-glob-to-any-file: '.devcontainer/**/*'

# Branch-based labels
breaking:
 - head-branch: ['^breaking', 'breaking', 'major']

feature:
 - head-branch: ['^feature', 'feature', 'enhancement', 'feat', 'add', 'minor']

bugfix:
 - head-branch: ['^bugfix', 'bugfix', 'fix', 'patch', 'hotfix']

 # Conventional Commit-based labels
conventional-commits:
- type: 'bugfix'
  nouns: ['bugfix', 'fix', 'patch', 'hotfix']
  labels: ['bugfix']
- type: 'feature'
  nouns: ['feature', 'enhancement', 'feat', 'add', 'minor']
  labels: ['feature']
- type: 'breaking'
  nouns: ['breaking', 'major']
  labels: ['breaking']
- type: 'docs'
  nouns: ['document','documentation']
  labels: ['docs']
- type: 'build'
  nouns: ['build','rebuild']
  labels: ['build']
- type: 'performance'
  nouns: ['performance', 'optimize', 'optimization']
  labels: ['performance']
- type: 'config'
  nouns: ['config', 'conf', 'cofiguration', 'configure']
  labels: ['config']
