name: Run Integration Tests
description: Run PowerShell integration tests using Pester
runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.0.x'

    - name: Build Module
      shell: pwsh
      run: |
        dotnet restore './PSBinaryModule.sln'
        dotnet build './PSBinaryModule.sln' --configuration Release --no-restore

        if (Get-Command Invoke-Build -ErrorAction SilentlyContinue) {
          Invoke-Build -Task Build -Configuration Release
        } else {
          Install-Module InvokeBuild -Force -SkipPublisherCheck
          Invoke-Build -Task Build -Configuration Release
        }

    - name: Install PowerShell
      shell: pwsh
      run: |
        if ($env:RUNNER_OS -eq 'Linux') {
          sudo apt-get update
          sudo apt-get install -y powershell
        } elseif ($env:RUNNER_OS -eq 'macOS') {
          brew install --cask powershell
        }

    - name: Install Pester
      shell: pwsh
      run: |
        Install-Module Pester -Force -SkipPublisherCheck

    - name: Configure .NET Environment
      shell: pwsh
      run: |
        $dotnetInfo = & dotnet --info
        $sdkPath = $dotnetInfo | Select-String "Base Path:" | ForEach-Object { $_.Line -replace '.*Base Path:\s*', '' }
        if ($sdkPath) {
          $dotnetRoot = Split-Path -Parent (Split-Path -Parent $sdkPath)
          echo "DOTNET_ROOT=$dotnetRoot" >> $env:GITHUB_ENV
          echo "DOTNET_MULTILEVEL_LOOKUP=1" >> $env:GITHUB_ENV
          Write-Host "DOTNET_ROOT set to: $dotnetRoot"
        }

    - name: Run Integration Tests
      shell: pwsh
      env:
        DOTNET_ROOT: ${{ env.DOTNET_ROOT }}
        DOTNET_MULTILEVEL_LOOKUP: ${{ env.DOTNET_MULTILEVEL_LOOKUP }}
      run: |
        Import-Module Pester
        $config = New-PesterConfiguration @{
            Run        = @{
                Path     = './tests/Integration'
                PassThru = $true
            }
            TestResult = @{
                Enabled      = $true
                OutputFormat = 'NUnitXml'
                OutputPath   = './test-results/integration-tests.xml'
            }
            Filter     = @{
                Tag = 'Integration'
            }
            Output     = @{
                Verbosity = 'Detailed'
            }
        }
        Invoke-Pester -Configuration $config

    - name: Upload test results
      uses: actions/upload-artifact@v6
      if: always()
      with:
        name: integration-test-results-${{ matrix.os }}
        path: test-results/
