name: Build PowerShell Module
description: Build module, generate help, and upload artifacts
inputs:
  release-type:
    description: Type of release (Release, Prerelease, Debug)
    default: Debug
    required: false
outputs:
  build-version:
    description: Semantic build version
    value: ${{ steps.compute.outputs.build-version }}
  release-version:
    description: Release version from GitVersion
    value: ${{ steps.gitversion.outputs.majorMinorPatch }}
runs:
  using: composite
  steps:

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install GitVersion tool
      uses: gittools/actions/gitversion/setup@d0139503a9321f76b4a417dfdc8aebcec24decdd #v4.2.0
      with:
        versionSpec: '6.5.1'

    - name: Get semantic build version
      id: gitversion
      uses: gittools/actions/gitversion/execute@d0139503a9321f76b4a417dfdc8aebcec24decdd #v4.2.0
      with:
        configFilePath: GitVersion.yml
        disableShallowCloneCheck: true

    - name: Setup PowerShell
      shell: pwsh
      run: |
        Install-PSResource -Name InvokeBuild -TrustRepository -AcceptLicense

    - name: Build Module
      shell: pwsh
      run: |
        Invoke-Build -Task Build -SemanticVersion ${{ steps.gitversion.outputs.MajorMinorPatch }} -Configuration ${{ inputs.release-type }}

    - name: Create NuGet package from build artifacts
      shell: pwsh
      run: |
        Set-StrictMode -Version Latest
        [void] (Import-Module InvokeBuild)
        Invoke-Build -Task Package

    - name: Upload NuGet package
      id: upload_nuget
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}.${{ steps.gitversion.outputs.MajorMinorPatch }}.nupkg
        path: build/package/${{ github.event.repository.name }}.${{ steps.gitversion.outputs.MajorMinorPatch }}.nupkg

    - name: Upload module bin artifacts
      id: upload_bin
      uses: actions/upload-artifact@v4
      with:
        name: PSBinaryModule
        path: build/out/PSBinaryModule
