name: Release PowerShell Module
description: Create GitHub release and optionally publish to PSGallery
inputs:
  release-type:
    description: Release type
    required: true
  release-version:
    description: Release version
    required: true
  publish-psgallery:
    description: Publish to PowerShell Gallery
    required: true
secrets:
  PSGALLERY_API_KEY:
    description: API Key for PowerShell Gallery
    required: false
runs:
  using: composite
  steps:
    - name: Generate release notes
      shell: pwsh
      id: generate_release_notes
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        git fetch --tags
        $tags = @(git tag --sort=-v:refname)
        $previousTag = if ($tags.Count -gt 0) { $tags[0] } else { $null }
        $uri = "https://api.github.com/repos/${{ github.repository }}/releases/generate-notes"
        $body = @{
          tag_name = "v${{ inputs.release-version }}"
          target_commitish = "main"
        }
        # Only include previous_tag_name if a previous tag exists
        if ($previousTag) {
          $body['previous_tag_name'] = $previousTag
        }
        $requestParams = @{
          Method      = 'Post'
          Uri         = $uri
          Headers     = @{
            Authorization = "Bearer ${{ env.GITHUB_TOKEN }}"
            Accept        = 'application/vnd.github+json'
          }
          Body        = ($body | ConvertTo-Json -Depth 3)
          ContentType = 'application/json'
        }
        $result = Invoke-RestMethod @requestParams
        Write-Output 'releaseNotes<<EOF' >> $env:GITHUB_OUTPUT
        Write-Output ($result.body.ToString()) >> $env:GITHUB_OUTPUT
        Write-Output 'EOF' >> $env:GITHUB_OUTPUT

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ inputs.release-version }}
        release_name: Release v${{ inputs.release-version }}
        body: ${{ steps.generate_release_notes.outputs.releaseNotes }}
        draft: false
        prerelease: ${{ inputs.release-type == 'Prerelease' }}

    - name: Publish build package to PSGallery
      if: ${{ inputs.publish-psgallery == 'true' && env.PSGALLERY_API_KEY != '' }}
      shell: pwsh
      run: |
        Set-StrictMode -Version Latest
        [void] (Import-Module InvokeBuild)
        Invoke-Build -NugetApiKey ${{ env.PSGALLERY_API_KEY }} -Task Publish

    - name: Upload build package to Github Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/package/${{ github.event.repository.name }}.${{ inputs.release-version }}.nupkg
        asset_name: ${{ github.event.repository.name }}-v${{ inputs.release-version }}.nupkg
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ github.token }}
